### ISSUE TITLE
Create pool from json does not run pool-task as custom user

### ISSUE THREAD

**Issue by kim0** [Azure/azure-batch-cli-extensions#30]
Attempting to create a batch pool using the below json file (--json-file)
[mon03support.txt](https://github.com/Azure/azure-batch-cli-extensions/files/1163848/mon03support.txt)

The pool comes up, however the pool-task is NOT run under user (kim0) which is the expected behavior. Instead it is run under some other _azbatch user account (which does not have sudo powers). Am I missing something in the json, or is this a bug

Thanks

**Comment by itowlson** [comment]
What version of the CLI batch and batch-extensions modules are you on?  I've noticed that CLI 2 tends to overlook JSON fields it doesn't understand rather than complaining about them (which I feel is a bug **grin**), so if it's using an API version from before we had user accounts support, it would be ignoring your startTask.userIdentity and so you'd be getting default identify behaviour instead.

If you run `az --version` and let us know the versions for `batch` and `batch-extensions` we can map that to an API version and determine if this is indeed the problem...

**Comment by kim0** [comment]
Thanks @itowlson .. It seems I only have batch
```
az --version | grep batch
batch (3.0.3)
```

**Comment by itowlson** [comment]
Cool, you wouldn't need batch-extensions for creating a pool -- I was just asking because you posted in the batch-extensions repo so thought you might be using extended features.  Thanks for the info -- unfortunately it might shoot my theory in the head, as 3.0.3 is pretty recent and the user identity feature was implemented in the January 2017 API release.  @annatisch, should 3.0.3 support that API version?

**Comment by kim0** [comment]
So, the GUI (Azure portal), allows me to create a pool, create an admin user on that pool (on all nodes), put some bash code for pool-start-task, and run that start task under the user account I just created.

Can you please guide me how to achieve this with minimal number of steps / json files ?

I've read the documentation carefully, and I think I'm doing all steps as they should be. ie. Creating a user with elevation = admin, and specifying that same username in userIdentity under the pool-task. However it seems that the commands do NOT run under the user kim0 created, and thus does not have access to sudo. 

@annatisch @itowlson I'm really trying to get this project done before next week, it would be really great if you guys could give me some pointers before the weekend. Thanks for your help & support so far! Great job

**Comment by annatisch** [comment]
Hi @kim0,
There seems to be a couple of things in play here.
I think the correct capitalization of `userName` should be all lower case:
```
"startTask": {
    "commandLine": "/bin/sh -c 'sudo apt-add-repository ppa:ansible/ansible -y && sudo apt update && sudo apt install -y git ansible'",
    "environmentSettings": [],
    "maxTaskRetryCount": 0,
    "resourceFiles": [],
    "userIdentity": {
      "username": "kim0"
    },
    "waitForSuccess": false
},
```
This seems strange given that it's [documented in the API as camel case
](https://docs.microsoft.com/en-us/rest/api/batchservice/add-a-task-to-a-job#userIdentity) and indeed a GET request on a pool will return this value as camel case, but the PUT request only seems to accept the value in lower case. Perhaps @itowlson has some insight on this convention?
I agree with Ivan that the CLI should probably raise an error, or display a warning if it encounters attributes it doesn't recognize.

Additionally, if you're using the extended CLI, I've encountered a bug in the handling of pool OS detection that is doing some interesting things with the command line. I will try to publish a bug fix release today.

**Comment by annatisch** [comment]
Okay, I have a workaround to the pool OS detection bug in the meantime - by using bash rather than shell for the command line. My final pool create JSON looks like this:
```
{
    "displayName": "mon03",
    "id": "mon03",
    "userAccounts": [
      {
        "elevationLevel": "admin",
        "name": "kim0",
        "password": "XXXxx%XXXX"
      }
    ],
    "resizeTimeout": "P1DT00H",
    "startTask": {
      "commandLine": "/bin/bash -c 'sudo apt-add-repository ppa:ansible/ansible -y && sudo apt update && sudo apt install -y git ansible'",
      "userIdentity": {
        "username": "kim0"
      },
      "waitForSuccess": false
    },
    "targetDedicatedNodes": 0,
    "targetLowPriorityNodes": 1,
    "taskSchedulingPolicy": {
      "nodeFillType": "pack"
    },
    "virtualMachineConfiguration": {
      "imageReference": {
        "offer": "UbuntuServer",
        "publisher": "Canonical",
        "sku": "16.04-LTS",
        "version": "latest"
      },
      "nodeAgentSKUId": "batch.node.ubuntu 16.04"
    },
    "vmSize": "standard_f4"
}
```

It's worth noting that despite the fact that the userIdentity is set on the startTask, for some reason this does not display in the portal. However the start task completes successfully with the required admin privileges, and if I remove the userIdentity field from the startTask it fails as expected.

**Comment by annatisch** [comment]
@kim0,
On further investigation it seems like change between `userName` -> `username` is not in our API, this is the same capitalization issue with the CLI core that you're seeing with `nodeAgentSKUId`.
I'll add a reference to this in my CLI issue.

@itowlson - this also means that our API documentation for this field is incorrect ;)

**Comment by kim0** [comment]
Thanks a lot @annatisch for your great investigation there! Thanks for the fix/workaround, I'll be sure to test it soon!

**Comment by kim0** [comment]
Just to confirm that changing username to lower-case does make the task run successfully. Thanks for that and hoping this letter-case thing gets resolved as it seems I've hit it multiple times.

**Comment by annatisch** [comment]
Great! Thanks for the confirmation @kim0 :)
I will leave this and #29 open until I get further guidance on whether and how the CLI core will address this capitalization issue.

**Comment by xingwu1** [comment]
Close this issue. Since we treat the username as a word, instead "user name".
